spring:
  application:
    name: big-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/big_event?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
server:
  port: 9090
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
aliyun:
  oss:
    accessKeyId: xxx # 视情况而定
    accessKeySecret: xxx # 视情况而定
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: xxx # 视情况而定
